### ISSUE TITLE
Encrypting bearer token does not improve security

### ISSUE THREAD

**Issue by redfast00** [fjaderboll/pytradfri-rest#1]
The current implementation (https://github.com/fjaderboll/pytradfri-rest/blob/master/rest/utils.py) is not really better than just leaving the token in plaintext: encrypting with a fixed key is almost equal to not encrypting at all; this just relies on obscurity. However, I understand what led to this decision: if you want to have a dynamic key, you have to have some kind of persistence, which is more work to implement.

**Comment by fjaderboll** [comment]
I agree. I rewrote this now so the key is read from a manually generated file (create-crypt-key.sh). This way each installation will get its own unique key.

**Comment by fjaderboll** [comment]
I agree. I rewrote this now so the key is read from a manually generated file (create-crypt-key.sh). This way each installation will get its own unique key.
